project_id = "kayttwmmdcubfjqrpztw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://5ed76bfc-5970-43c6-beda-83a586a98566.sandbox.lovable.dev"]
jwt_expiry = 3600

[db]
port = 54322

[edge_functions]
enabled = true
port = 54323

[functions.gekko-proxy]
verify_jwt = false

[functions.gekko-light-control]
verify_jwt = false

[functions.energy-ai-analysis]
verify_jwt = false

[functions.energy-ai-analysis-simple]
verify_jwt = false

[functions.energy-bulk-import]
verify_jwt = false

[functions.energy-ml-analysis]
verify_jwt = false

[functions.gekko-multi-import]
verify_jwt = false

[functions.assistant-route]
verify_jwt = false

[functions.prophet-forecast]
verify_jwt = false

[functions.open-meteo-weather]
verify_jwt = false

[functions.openems-bridge]
verify_jwt = false